spring.datasource.url=jdbc:postgresql://users-service:5432/users_db
spring.datasource.username=
spring.datasource.password=

spring.cloud.consul.host=consul
#spring.cloud.consul.discovery.ip-address=192.168.100.2
#spring.cloud.consul.discovery.hostname=users-service.local
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=15s

management.endpoints.web.exposure.include=health

