spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5435/users
spring.datasource.username=postgres
spring.datasource.password=pass
