server.port=8081
spring.application.name=course-service

spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true

jwt.secret=e0fe6d3206687750f0d028ad09dfbf59
jwt.expiration=60000

spring.cloud.openfeign.circuitbreaker.enabled=true


