package com.teachsync.notificationservice.domain;

public enum TargetSubject {
    COURSE_CREATED,
    COURSE_UPDATED,
    COURSE_GROUP_ENROLLED,
    COURSE_GROUP_REMOVED,
    COURSE_TOPIC_ADDED,
    COURSE_TOPIC_REMOVED,
    COURSE_TEACHER_UNASSIGNED,
    TEACHER_ASSIGNMENT_REQUESTED,
    TEACHER_ASSIGNED,
    SCHEDULE_CREATED,
    USER_CREATED,
    USER_DELETED,
    USER_ROLE_CHANGED,
    USER_SPECIALIZATION_ADDED,
    USER_SPECIALIZATION_REMOVED,
    REPLACEMENT_REQUESTED,
    REPLACEMENT_APPROVED,
    REPLACEMENT_STATUS_CHANGED
}
