spring.application.name=api-gateway
server.port=8080

# USERS
spring.cloud.gateway.routes[0].id=users-service
spring.cloud.gateway.routes[0].uri=${USERS_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[0].predicates[0]=Path=/teachsync/users/**

# AUTH
spring.cloud.gateway.routes[1].id=auth-service
spring.cloud.gateway.routes[1].uri=${AUTH_SERVICE_URL:http://localhost:8090}
spring.cloud.gateway.routes[1].predicates[0]=Path=/teachsync/auth/**

# ACCOUNT
spring.cloud.gateway.routes[2].id=account-service
spring.cloud.gateway.routes[2].uri=${AUTH_SERVICE_URL:http://localhost:8090}
spring.cloud.gateway.routes[2].predicates[0]=Path=/teachsync/account/**

# COURSES
spring.cloud.gateway.routes[3].id=courses-service
spring.cloud.gateway.routes[3].uri=${COURSE_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[3].predicates[0]=Path=/teachsync/courses/**

# TOPICS
spring.cloud.gateway.routes[4].id=topics-service
spring.cloud.gateway.routes[4].uri=${COURSE_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[4].predicates[0]=Path=/teachsync/topics/**

# CATEGORIES
spring.cloud.gateway.routes[5].id=categories-service
spring.cloud.gateway.routes[5].uri=${COURSE_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[5].predicates[0]=Path=/teachsync/categories/**

# SCHEDULES
spring.cloud.gateway.routes[6].id=schedule-service
spring.cloud.gateway.routes[6].uri=${SCHEDULE_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[6].predicates[0]=Path=/teachsync/schedules/**

# GROUPS
spring.cloud.gateway.routes[7].id=groups-service
spring.cloud.gateway.routes[7].uri=${COURSE_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[7].predicates[0]=Path=/teachsync/groups/**

# NOTIFICATIONS
spring.cloud.gateway.routes[8].id=notification-service
spring.cloud.gateway.routes[8].uri=${NOTIFICATION_SERVICE_URL:http://localhost:8085}
spring.cloud.gateway.routes[8].predicates[0]=Path=/teachsync/notifications/**

# REPLACEMENTS
spring.cloud.gateway.routes[9].id=replacement-service
spring.cloud.gateway.routes[9].uri=${REPLACEMENT_SERVICE_URL:http://localhost:8086}
spring.cloud.gateway.routes[9].predicates[0]=Path=/teachsync/replacements/**

# CLASSROOMS
spring.cloud.gateway.routes[10].id=classrooms-service
spring.cloud.gateway.routes[10].uri=${SCHEDULE_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[10].predicates[0]=Path=/teachsync/classrooms/**

logging.level.org.springframework.cloud.gateway=DEBUG
